### ISSUE TITLE
feat: Implement rate limiting & global asyncHandler

### ISSUE THREAD

**Issue by geekyharsh05** [10kumaranurag01/todo-done-express#4]
- Implement rate limitng
- Implement asyncHandlers to make the codesbase more clean.
- Request Logger 
- TestFile For Ratelimiter

@10kumaranurag01 Can you please assign this to me?

**Comment by 10kumaranurag01** [comment]
@geekyharsh05 Go ahead, fork it, create a new branch and make your amazing PRs.
