### ISSUE TITLE
 Implement Logout Functionality

### ISSUE THREAD

**Issue by yashanand167** [10kumaranurag01/todo-done-express#5]
The application currently lacks a logout feature, preventing users from securely logging out. Users should be able to log out, which would terminate their session and redirect them to the login page.

**Comment by 10kumaranurag01** [comment]
@yashanand167 This is currently under work.

**Comment by geekyharsh05** [comment]
@yashanand167 You can work on something else like caching using redis, if it is not under work then is it a feasible idea to implement? @10kumaranurag01 Thoughts?

**Comment by 10kumaranurag01** [comment]
Yes redis caching can be implemented.

**Comment by geekyharsh05** [comment]
@10kumaranurag01 Can i and @yashanand167 can do it together?
