### ISSUE TITLE
Implementation of TypeScript for better development 

### ISSUE THREAD

**Issue by Tholkappiar** [10kumaranurag01/todo-done-express#7]
**Suggested Improvements :**

- Integrating TypeScript in the codebase for better development , suggestions and to avoid unexpected errors !

_PS : Assign this issue to me under hacktoberfest 2024 , if you'r comfortable with the above changes or feats !_

**Comment by geekyharsh05** [comment]
@Tholkappiar Many things are already under work, it'll break some things.

**Comment by 10kumaranurag01** [comment]
@Tholkappiar Let the codebase finish some major reworks, then i will open this enahncement.

**Comment by Tholkappiar** [comment]
Okay no problem !
