### ISSUE TITLE
feat: Implement redis for caching.

### ISSUE THREAD

**Issue by geekyharsh05** [10kumaranurag01/todo-done-express#9]
- [ ] Add redis for caching
- [ ] Accordingly update the docker compose to accomodate redis.
- [ ] Update the readme file too for easy setup.

Add this under hacktoberfest lable @10kumaranurag01.

**Comment by geekyharsh05** [comment]
@yashanand167 If you want to work you can take it.

**Comment by yashanand167** [comment]
Sure

**Comment by 10kumaranurag01** [comment]
Can you explain, what this will achieve?
